### ISSUE TITLE
Where can I find Minwiki dataset?

### ISSUE THREAD

**Issue by sophiayyya** [serenayj/DeSSE#1]
Hi, 

Thanks for your great dataset for sentence simplification. I read your paper in ACL2021 and I am wondering where can I find Minwiki dataset. In paper ACL2021, I saw that you indicated that in this repo Minwiki dataset could be found.

Thanks in advance!

**Comment by serenayj** [comment]
Hi, 

Thank you for pointing out the Minwiki data is missing! My fault! I will upload them soon (by today) and will let you know!

**Comment by sophiayyya** [comment]
> Hi,
> 
> Thank you for pointing out the Minwiki data is missing! My fault! I will upload them soon (by today) and will let you know!

Thanks a lot for your quick reply!

**Comment by sophiayyya** [comment]
Hi, 

Have you uploaded Minwiki dataset?  Sorry, I don't find them. 
Thanks in advance.

**Comment by serenayj** [comment]
Hi, 

Sorry for the late reply. The dataset sits on a server in a lab that I previously work. I move to a new lab so I am waiting for help to transit the data out. Thank you for your patience. I do have the source codes to re-generate MinWiki if you are in urgent need (Or I could re-generate for you). Although it will take a while to run.

**Comment by serenayj** [comment]
Hi, I have updated the repo with the MinWiki corpus. Let me know if there is any question.

**Comment by sophiayyya** [comment]
Yes! I can download this dataset. Thanks a lot!
